server:
  port: 9001
  servlet:
    context-path: /big-data-hbase
#swagger
swagger:
  enable: true

hbase:
  master: nna:16010
  zookeeper:
    quorum: dn1,dn2,dn3
    property:
      clientPort: 2181

zookeeper:
  znode:
    parent: /hbase